# Generated by Django 4.0.5 on 2022-06-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_messagethrough_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagethrough',
            name='recipient',
        ),
    ]
