# Generated by Django 4.0.5 on 2022-06-07 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
