# Generated by Django 4.0.5 on 2022-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_messages_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
